project:
  type: website
  output-dir: _site

website:
  title: "Abhinav Choudhary"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: steering-methods.qmd
        text: Blogs

format:
  html:
    theme: cosmo
    toc: true
